alias: Obico Webhook
description: Receive Obico server Notifications
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: "CHANGE-ME"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'FilamentChange' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            metadata: {}
            data:
              message: |-
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Printer requires attention!
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'PrintCancelled' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            data:
              message: |-
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has been cancelled
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'PrintDone' in trigger.json.event.type }}"
        sequence:
          - delay: "00:05:00"
          - action: notify.mobile_app_sm_g780g
            data:
              message: |-
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has completed
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'PrintFailure' in trigger.json.event.type }}"
        sequence:
          - action: camera.snapshot
            data:
              filename: /config/www/obico/print_issue.jpg
            target:
              entity_id: camera.192_168_1_30
          - action: notify.mobile_app_sm_g780g
            metadata: {}
            data:
              message: Attention! Possible failure during print!
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintPaused' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            data:
              message: |-
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has paused
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'PrintResumed' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            data:
              message: |-
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has resumed
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'PrintStarted' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            data:
              message: |-
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has started
                Filename: `{{ trigger.json.print.filename }}`
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'HeaterCooledDown' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            data:
              message: Payload {{ trigger.json }}
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'HeaterTargetReached' in trigger.json.event.type }}"
        sequence:
          - action: notify.mobile_app_sm_g780g
            data:
              message: Payload {{ trigger.json }}
              title: "*Obico Server:* {{ trigger.json.printer.name }}"
