blueprint:
  name: Obico Webhook
  description: Receive Obico server notifications via webhook and notify a mobile app.
  domain: automation
  input:
    webhook_id:
      name: Webhook ID
      description: The webhook ID to listen for.
      selector:
        text:
    camera_entity:
      name: Camera Entity
      description: Camera entity for capturing snapshots (used for print failures).
      selector:
        entity:
          domain: camera

trigger:
  - platform: webhook
    webhook_id: !input webhook_id
    allowed_methods:
      - POST
      - PUT
    local_only: true

condition: []

action:
  - service: camera.snapshot
    target:
      entity_id: !input camera_entity
    data:
      filename: /config/www/obico/print_issue.jpg
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'FilamentChange' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: >
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Printer requires attention! Time to change filament!
              title: "Obico Server: {{ trigger.json.printer.name }}"
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintCancelled' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: >
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has been cancelled!
              title: "Obico Server: {{ trigger.json.printer.name }}"
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintDone' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: >
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has completed!
              title: "Obico Server: {{ trigger.json.printer.name }}"
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintFailure' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: Attention! Possible failure during print!
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintPaused' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: >
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has paused
              title: "Obico Server: {{ trigger.json.printer.name }}"
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintResumed' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: >
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has resumed
              title: "Obico Server: {{ trigger.json.printer.name }}"
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'PrintStarted' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: >
                Date: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}

                Print has started
                Filename: `{{ trigger.json.print.filename }}`
              title: "Obico Server: {{ trigger.json.printer.name }}"
              data:
                image: /media/local/obico/print_issue.jpg
      - conditions:
          - condition: template
            value_template: "{{ 'HeaterCooledDown' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: Heater cooled down.
              title: "Obico Server: {{ trigger.json.printer.name }}"
      - conditions:
          - condition: template
            value_template: "{{ 'HeaterTargetReached' in trigger.json.event.type }}"
        sequence:
          - service: notify.notify
            data:
              message: Heater target reached.
              title: "Obico Server: {{ trigger.json.printer.name }}"
mode: parallel
max: 2
